Switched to branch 'daily'
ERROR:azure.storage.common.storageclient:Client-Request-ID=c1d25faf-6da1-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 18:03:34 GMT, Server-Request-ID=048eab94-001e-0031-2aae-01c4ba000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:048eab94-001e-0031-2aae-01c4ba000000Time:2018-06-11T18:03:35.5593672Z</Message></Error>.
ERROR:azure.storage.common.storageclient:Client-Request-ID=c1d25fb1-6da1-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 18:03:34 GMT, Server-Request-ID=aea467b2-001e-006c-5eae-01ce3e000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:aea467b2-001e-006c-5eae-01ce3e000000Time:2018-06-11T18:03:35.7149769Z</Message></Error>.
ERROR:azure.storage.common.storageclient:Client-Request-ID=c1d25fb3-6da1-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 18:03:35 GMT, Server-Request-ID=6fe15440-f01e-0035-37ae-0149bd000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:6fe15440-f01e-0035-37ae-0149bd000000Time:2018-06-11T18:03:35.8734031Z</Message></Error>.
ERROR:azure.storage.common.storageclient:Client-Request-ID=c1d25fb5-6da1-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 18:03:35 GMT, Server-Request-ID=ce6cb765-c01e-004c-7eae-01b599000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:ce6cb765-c01e-004c-7eae-01b599000000Time:2018-06-11T18:03:36.0358466Z</Message></Error>.
Traceback (most recent call last):
  File "./02.local.py", line 92, in <module>
    min(metrics['mse']), 
KeyError: 'mse'
ERROR:azure.storage.common.storageclient:Client-Request-ID=7d8af594-6dac-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 19:20:24 GMT, Server-Request-ID=fd37a70c-501e-0061-60b9-0106ea000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:fd37a70c-501e-0061-60b9-0106ea000000Time:2018-06-11T19:20:24.3943849Z</Message></Error>.
ERROR:azure.storage.common.storageclient:Client-Request-ID=7d8af596-6dac-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 19:20:24 GMT, Server-Request-ID=6fe27627-f01e-0035-59b9-0149bd000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:6fe27627-f01e-0035-59b9-0149bd000000Time:2018-06-11T19:20:24.5485404Z</Message></Error>.
ERROR:azure.storage.common.storageclient:Client-Request-ID=7d8af598-6dac-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 19:20:24 GMT, Server-Request-ID=ce6dd81c-c01e-004c-41b9-01b599000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:ce6dd81c-c01e-004c-41b9-01b599000000Time:2018-06-11T19:20:24.7046746Z</Message></Error>.
ERROR:azure.storage.common.storageclient:Client-Request-ID=7d8af59a-6dac-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Mon, 11 Jun 2018 19:20:24 GMT, Server-Request-ID=5c277572-d01e-0022-35b9-01e0b6000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:5c277572-d01e-0022-35b9-01e0b6000000Time:2018-06-11T19:20:24.8644699Z</Message></Error>.
Traceback (most recent call last):
  File "./10.o16n.py", line 88, in <module>
    model.delete()
  File "/home/ninghai/miniconda3/envs/daily/lib/python3.6/site-packages/azureml/core/model.py", line 313, in delete
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 412
Headers: {'Date': 'Mon, 11 Jun 2018 19:27:33 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': '1813449173054481a892f62043068bae', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"PreconditionFailed","statusCode":412,"message":"PreconditionFailed","details":[{"code":"DeletionRequired","message":"The model with id mymodel:1 can not be deleted because it is currently being used in one or more images"}]}'
Switched to branch 'master'
