Switched to branch 'candidate'
Client-Request-ID=a5efaab5-6e62-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 12 Jun 2018 17:04:20 GMT, Server-Request-ID=52438fb3-a01e-00ff-646f-0269a9000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:52438fb3-a01e-00ff-646f-0269a9000000Time:2018-06-12T17:04:21.1146581Z</Message></Error>.
Client-Request-ID=a5efaab7-6e62-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 12 Jun 2018 17:04:20 GMT, Server-Request-ID=d01bf5b9-101e-004c-116f-02932e000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:d01bf5b9-101e-004c-116f-02932e000000Time:2018-06-12T17:04:21.3545081Z</Message></Error>.
Client-Request-ID=a5efaab9-6e62-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 12 Jun 2018 17:04:21 GMT, Server-Request-ID=95cff9b1-701e-005c-5d6f-02a5c8000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:95cff9b1-701e-005c-5d6f-02a5c8000000Time:2018-06-12T17:04:21.5126532Z</Message></Error>.
Client-Request-ID=a5efaabb-6e62-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 12 Jun 2018 17:04:20 GMT, Server-Request-ID=f4a0cbd4-c01e-0045-796f-0289a0000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:f4a0cbd4-c01e-0045-796f-0289a0000000Time:2018-06-12T17:04:21.6845527Z</Message></Error>.
Traceback (most recent call last):
  File "./02.local.py", line 92, in <module>
    min(metrics['mse']), 
KeyError: 'mse'
Client-Request-ID=46c51079-6e68-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 12 Jun 2018 17:44:38 GMT, Server-Request-ID=1a50d844-d01e-00bf-3f75-024047000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:1a50d844-d01e-00bf-3f75-024047000000Time:2018-06-12T17:44:38.9305965Z</Message></Error>.
Client-Request-ID=4790de2e-6e68-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 12 Jun 2018 17:44:38 GMT, Server-Request-ID=ac53a1e7-901e-007f-3375-02ca03000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:ac53a1e7-901e-007f-3375-02ca03000000Time:2018-06-12T17:44:39.2220751Z</Message></Error>.
Client-Request-ID=4790de30-6e68-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 12 Jun 2018 17:44:38 GMT, Server-Request-ID=c190bae2-701e-003a-3175-021792000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:c190bae2-701e-003a-3175-021792000000Time:2018-06-12T17:44:39.4033411Z</Message></Error>.
Client-Request-ID=4790de32-6e68-11e8-9288-000d3a71b7c3 Retry policy did not allow for a retry: Server-Timestamp=Tue, 12 Jun 2018 17:44:39 GMT, Server-Request-ID=4134d968-b01e-00c2-3875-02dc8f000000, HTTP status code=409, Exception=The specified container already exists.ErrorCode: ContainerAlreadyExists<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.RequestId:4134d968-b01e-00c2-3875-02dc8f000000Time:2018-06-12T17:44:39.5731610Z</Message></Error>.
Traceback (most recent call last):
  File "./10.o16n.py", line 88, in <module>
    model.delete()
  File "/home/ninghai/miniconda3/envs/candidate/lib/python3.6/site-packages/azureml/core/model.py", line 313, in delete
    'Content: {}'.format(resp.status_code, resp.headers, resp.content))
azureml.exceptions.azureml_exception.WebserviceException: Received bad response from Model Management Service:
Response Code: 412
Headers: {'Date': 'Tue, 12 Jun 2018 17:51:56 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'api-supported-versions': '2018-03-01-preview', 'x-ms-client-request-id': 'f79dddd6b5e0455697c0aab178c39d26', 'x-ms-client-session-id': '', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains; preload'}
Content: b'{"code":"PreconditionFailed","statusCode":412,"message":"PreconditionFailed","details":[{"code":"DeletionRequired","message":"The model with id best_model.pkl:189 can not be deleted because it is currently being used in one or more images"}]}'
Switched to branch 'master'
